<?php
/**
 * Global template tag convenience functions for the Pikari Team plugin.
 *
 * These functions are thin wrappers around Template_Tags static methods,
 * providing a familiar WordPress-style API for use in theme templates.
 *
 * @package pikari-team
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Returns a structured data array for a team member.
 *
 * @param int $post_id The team member post ID.
 * @return array<string, mixed>
 */
function pikari_team_get_member_data( int $post_id ): array {
    return \Pikari\Team\Template_Tags::get_member_data( $post_id );
}

/**
 * Returns a formatted address string for a team member.
 *
 * @param int $post_id The team member post ID.
 * @return string
 */
function pikari_team_get_address( int $post_id ): string {
    return \Pikari\Team\Template_Tags::get_formatted_address( $post_id );
}

/**
 * Outputs a formatted address string for a team member.
 *
 * @param int $post_id The team member post ID.
 */
function pikari_team_the_address( int $post_id ): void {
    echo esc_html( \Pikari\Team\Template_Tags::get_formatted_address( $post_id ) );
}

/**
 * Returns an array of populated social link entries for a team member.
 *
 * @param int $post_id The team member post ID.
 * @return array<int, array{platform: string, url: string, label: string}>
 */
function pikari_team_get_social_links( int $post_id ): array {
    return \Pikari\Team\Template_Tags::get_social_links( $post_id );
}

/**
 * Outputs the SVG QR code for a team member's vCard.
 *
 * @param int $post_id The team member post ID.
 */
function pikari_team_the_qr_code( int $post_id ): void {
    if ( ! class_exists( '\Pikari\Team\QR_Code' ) ) {
        return;
    }
    $qr = new \Pikari\Team\QR_Code();
    // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- SVG generated by plugin.
    echo $qr->generate_qr_svg( $post_id );
}
